askcos/askcos_site/urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()
import django.contrib.auth.urls
from django.views.generic import TemplateView
import askcos_site.main.views as views
from askcos_site import api

# Static (not good for deployment)
urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

# The rest
urlpatterns += [
    # Examples:
    # re_path(r'^$', 'askcos_site.views.home', name='home'),
    # re_path(r'^blog/', include('blog.urls')),

    re_path(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
    re_path(r'^examples/$', TemplateView.as_view(template_name='examples.html')),

    # Admin page
    path('admin/', admin.site.urls),

    # User pages
    path('registration/', include('django_registration.backends.one_step.urls')),
    path('registration/', include('django.contrib.auth.urls')),

    # Homepage
    re_path(r'^$', views.index, name='index'),
    re_path(r'^help/modules$', views.modules, name='modules'),
    re_path(r'^help/tutorial$', views.tutorial, name='tutorial'),
    re_path(r'^help/faq$', views.faq, name='faq'),

    # Retrosynthesis
    re_path(r'^retro/$', views.retro, name='retro_home'),
    re_path(r'^retro/target=(?P<smiles>.+)$', views.retro_target, name='retro_target'),

    # Interactive retrosynthesis
    re_path(r'^retro_interactive/$', views.retro_interactive, name='retro_interactive'),
    re_path(r'^retro_interactive/target=(?P<target>.+)$', views.retro_interactive, name='retro_interactive_target'),
    re_path(r'^retro_interactive_mcts/$', views.retro_interactive_mcts, name='retro_interactive_mcts'),
    re_path(r'^retro_interactive_mcts/target=(?P<target>.+)$', views.retro_interactive_mcts, name='retro_interactive_mcts_target'),
    re_path(r'^ajax/smiles_to_image/$', views.ajax_smiles_to_image, name='ajax_smiles_to_image'),
    re_path(r'^ajax/rxn_to_image/$', views.ajax_rxn_to_image, name='ajax_rxn_to_image'),
    re_path(r'^ajax/start_retro_celery/$', views.ajax_start_retro_celery, name='ajax_start_retro_celery'),
    re_path(r'^ajax/start_retro_mcts_celery/$', views.ajax_start_retro_mcts_celery, name='ajax_start_retro_mcts_celery'),
    re_path(r'^retro_interactive/export/(?P<_id>.+)$', views.export_retro_results, name='export_retro_results'),

    # Evaluation
    re_path(r'^evaluate/$', views.evaluate_rxnsmiles, name='evaluate_rxnsmiles'),
    re_path(r'^ajax/evaluate_rxnsmiles/$', views.ajax_evaluate_rxnsmiles, name='ajax_evaluate_rxnsmiles'),

    # Context
    re_path(r'^context/$', views.context_rxnsmiles, name='context_rxnsmiles'),
    re_path(r'^context/reactants=(?P<reactants>.+)&product=(?P<product>.+)$', views.context_rxnsmiles_target2, name='context_rxnsmiles_target2'),
    re_path(r'^context/smiles=(?P<smiles>.+)$', views.context_rxnsmiles_target, name='context_rxnsmiles_target'),
    re_path(r'^ajax/context_rxnsmiles/$', views.ajax_context_rxnsmiles, name='ajax_context_rxnsmiles'),

    # Interactive forward prediction
    re_path(r'^synth_interactive/$', views.synth_interactive, name='synth_interactive'),
    re_path(r'^synth_interactive/reactants=(?P<reactants>.+)&reagents=(?P<reagents>.*)&solvent=(?P<solvent>.*)&temperature=(?P<temperature>.*)$', views.synth_interactive, name='synth_interactive_contextspec'),
    re_path(r'^synth_interactive/reactants=(?P<reactants>.+)&product=(?P<product>.+)$', views.synth_interactive, name='synth_interactive_target2'),
    re_path(r'^synth_interactive/reactants=(?P<reactants>.+)$', views.synth_interactive, name='synth_interactive_target'),
    re_path(r'^synth_interactive/smiles=(?P<smiles>.+)$', views.synth_interactive_smiles, name='synth_interactive_target_smiles'),
    re_path(r'^ajax/start_synth/$', views.ajax_start_synth, name='ajax_start_synth'),
    re_path(r'^synth_interactive/download$', views.export_synth_results, name='export_synth_results'),

    # Site Selectivity prediction
    re_path(r'^site_prediction/$', views.site_prediction, name='site_prediction'),
    re_path(r'^ajax/get_sites/$', views.ajax_get_sites, name='ajax_get_sites'),

    # Template examination (by str(ObjectID))
    re_path(r'^template/target=(?P<id>.+)$', views.template_target, name='template_target'),
    re_path(r'^template/download/target=(?P<id>.+)$', views.template_target_export, name='template_target_export'),

    # Reaction examination
    # re_path(r'^reaxys/rxid=(?P<rxid>.+)$', views.rxid_target, name='rxid_target'),

    # Historians
    # re_path(ur'^history/chemicals/(?P<smiles>.+)$', views.chemical_history_check, name='chemical_history'),
    # re_path(ur'^history/reactions/(?P<smiles>.+)$', views.reaction_history_check, name='reaction_history'),

    # Pricing
    re_path(r'^buyables/$', views.buyables, name='buyables'),

    # SCScore
    re_path(r'^scscore/$', views.scscoring, name='scscoring'),
    re_path(r'^ajax/scscore_smiles/$', views.ajax_scscore_smiles, name='ajax_scscore_smiles'),

    # Drawing
    re_path(r'^draw/$', views.draw, name='draw'),
    re_path(r'^draw/smiles/(?P<smiles>.+)$', views.draw_smiles, name='draw_smiles'),
    re_path(r'^draw/template/(?P<template>.+)$', views.draw_template, name='draw_template'),
    re_path(r'^draw/reaction/(?P<smiles>.+)$', views.draw_reaction, name='draw_reaction'),
    re_path(r'^draw/mapped_reaction/(?P<smiles>.+)$', views.draw_mapped_reaction, name='draw_mapped_reaction'),
    re_path(r'^draw/highlighted_reaction/(?P<smiles>.+)$', views.draw_highlighted_reaction, name='draw_highlighted_reaction'),

    re_path(r'^draw/highlight/smiles=(?P<smiles>.+)&reacting_atoms=(?P<reacting_atoms>.+)&bonds=(?P<bonds>.+)$', views.draw_smiles_highlight, name='draw_highlight'),

    # Separation
    # re_path(r'^separation/input/$', views.sep_input, name='sep_input'),
    re_path(r'^separation/draw/(?P<fig>.+)$', views.draw_fig, name='draw_fig'),

    # Nearest Neighbor Setup
    # re_path(r'^nnRecommendation/setup/$', views.nn_predictor_setup, name='setup'),

    # Saved data
    re_path(r'^saved/$', views.user_saved_results, name='user_saved_results'),
    re_path(r'^saved/id=(?P<_id>.+)$', views.user_saved_results_id, name='user_saved_results_id'),
    re_path(r'^ajax/user_save_page/$', views.ajax_user_save_page, name='ajax_user_save_page'),
    re_path(r'^saved/delete/id=(?P<_id>.+)$', views.user_saved_results_del, name='user_saved_results_del'),

    # Blacklisted reactions
    re_path(r'^blacklisted/reactions/$', views.user_blacklisted_reactions, name='user_blacklisted_reactions'),
    re_path(r'^ajax/user_blacklist_reaction/$', views.ajax_user_blacklist_reaction, name='ajax_user_blacklist_reaction'),
    re_path(r'^blacklisted/reactions/delete/id=(?P<_id>.+)$', views.user_blacklisted_reactions_del, name='user_blacklisted_reactions_del'),
    re_path(r'^ajax/user_deactivate_reaction/$', views.ajax_user_deactivate_reaction, name='ajax_user_deactivate_reaction'),
    re_path(r'^ajax/user_activate_reaction/$', views.ajax_user_activate_reaction, name='ajax_user_activate_reaction'),

    # Blacklisted chemicals
    re_path(r'^blacklisted/chemicals/$', views.user_blacklisted_chemicals, name='user_blacklisted_chemicals'),
    re_path(r'^ajax/user_blacklist_chemical/$', views.ajax_user_blacklist_chemical, name='ajax_user_blacklist_chemical'),
    re_path(r'^blacklisted/chemicals/delete/id=(?P<_id>.+)$', views.user_blacklisted_chemicals_del, name='user_blacklisted_chemicals_del'),
    re_path(r'^ajax/user_deactivate_chemical/$', views.ajax_user_deactivate_chemical, name='ajax_user_deactivate_chemical'),
    re_path(r'^ajax/user_activate_chemical/$', views.ajax_user_activate_chemical, name='ajax_user_activate_chemical'),

    # API endpoints
    re_path(r'^api/retro/$', api.retro.singlestep, name='retro_api'),
    re_path(r'^api/fast-filter/$', api.fast_filter.fast_filter, name='fast_filter_api'),
    re_path(r'^api/context/$', api.context.neural_network, name='context_api'),
    re_path(r'^api/forward/$', api.forward.template_free, name='forward_api'),
    re_path(r'^api/template/$', api.template.template, name='template_api'),
    re_path(r'^api/treebuilder/$', api.tree_builder.tree_builder, name='tree_builder_api'),
    re_path(r'^api/scscore/$', api.scscore.scscore, name='scscore_api'),
    re_path(r'^api/celery/$', api.status.celery_status, name='celery_api'),
    re_path(r'^api/validate-chem-name/$', api.validate_chem_name.validate_chem_name, name='validate_chem_name_api'),
    re_path(r'^api/buyables/search', api.buyables.buyables, name='all_buyables_api'),
    re_path(r'^api/buyables/add', api.buyables.add_buyable, name='add_buyables_api'),
    re_path(r'^api/buyables/upload', api.buyables.upload_buyable, name='upload_buyables_api'),
    re_path(r'^api/buyables/delete', api.buyables.delete_buyable, name='delete_buyables_api'),

    re_path(r'^api/cluster/$', api.cluster.cluster, name='cluster_api'),
    re_path(r'^api/selectivity/$', api.selectivity.selectivity, name='selectivity'),

    # async results
    re_path(r'^api/get-result/$', api.results.get_result, name='get_async_result'),
    re_path(r'^api/my-results/$', api.results.my_results, name='api_my_results'),
    re_path(r'^api/remove-result/$', api.results.remove_result, name='api_remove_results'),
    re_path(r'^api/poll-result/$', api.results.poll_result, name='api_poll_result'),
    re_path(r'^view-result/$', views.view_result, name='view_result'),
    re_path(r'^view-tree-graph/$', views.view_tree_graph, name='view_tree_graph'),
    re_path(r'^my-results/$', views.my_results, name='my_results'),

    # Reaction network
    re_path(r'^retro/network/$', views.retro_network, name='retro_network'),

    # Celery status
    re_path(r'^status/$', views.status),

    # Interactive impurity prediction

askcos/askcos_site/main/models.py
from django.db import models
from django.contrib.auth.models import User

class TreeResult(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    result_id = models.CharField(max_length=64)
    result_state = models.CharField(max_length=64)

class SavedResults(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000)
    created = models.DateTimeField('created on')
    dt = models.CharField(max_length=200)
    fpath = models.CharField(max_length=500)
    result_id = models.CharField(max_length=64)
    result_state = models.CharField(max_length=64)
    result_type = models.CharField(max_length=64)

class BlacklistedReactions(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000)
    created = models.DateTimeField('created on')
    dt = models.CharField(max_length=200)
    smiles = models.CharField(max_length=5000)
    active = models.BooleanField()

class BlacklistedChemicals(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000)
    created = models.DateTimeField('created on')
    dt = models.CharField(max_length=200)
    smiles = models.CharField(max_length=5000)
    active = models.BooleanField()

class SeparationInput(models.Model):
    tgt_smiles = models.CharField("Enter SMILES string of the target molecule", max_length=200)
    other_smiles = models.CharField('Enter SMILES strings of other solute molecules separated with comma',
                                   max_length=800)

    # Separation conditions
    org1 = models.CharField("Enter SMILES string of the organic solvent", max_length=200)
    org2 = models.CharField("Enter SMILES string of a second organic solvent and its molar fraction "
                            "separated with comma, otherwise 'None", max_length=200, blank=True)
    pH = models.FloatField("Enter the pH of the aqueous phase or blank", blank=True)
    ionic_strength = models.FloatField("Enter the ionic strength of the aqueous phase or blank", blank=True)

    temp = models.FloatField("Enter the separation temperature in Celsius degree or blank", blank=True)
    flow_ratio = models.FloatField("Enter the org/aqu flow rate ratio or blank", blank=True)

    # Optimization parameters
    OPT_CHOICES = (('h', 'pH_only'), ('f', 'flow_only'), ('b', 'both'))
    opt_option = models.CharField("What to vary: pH, flow or both:", max_length=1, choices=OPT_CHOICES)
    pH_step = models.FloatField('If to vary pH, enter the pH increment for optimization or blank', blank=True)
    flow_ratio_min = models.FloatField("If to vary org/aqu flow rate ratio, enter the minimum or blank", blank=True)
    flow_ratio_max = models.FloatField("If to vary org/aqu flow rate ratio, enter the maximum or blank", blank=True)
    num_flowratio = models.IntegerField("The number of flowratios in the range or blank", blank=True)

    PHASE_CHOICES = (('aqu', 'aqueous'), ('org', 'organic'), ('e', 'either'))
    max_phase = models.CharField("In which phase the target molecule should be concentrated:",
                                 max_length=3, choices=PHASE_CHOICES)
    min_phase = models.CharField("In which phase the target molecule should be minimized or leave blank:",
                                 max_length=3, choices=PHASE_CHOICES, blank=True)

    OPT_TGT_CHOICES = (('y', 'yield'), ('p', 'purity'), ('b', 'both'))
    opt_tgt_choice = models.CharField('Select the optimization target(s) of interest',
                                      max_length=1, choices=OPT_TGT_CHOICES)
    aqu_conc = models.CharField("If purity needed, enter the concentration for each molecule in the aqueous phase "
                                "and separate with comma", max_length=200)
    org_conc = models.CharField("If purity needed, enter the concentration for each molecule in the organic phase "
                                "and separate with comma", max_length=200)

    ##### TO DO:
        # solvent selection option
        # Score

    # def is_valid_pH(self):
    #     # Need to check whether this limit does exist
    #     if self.pH <= 14.0 and self.pH >= 0.0:
    #         return True
    #
    # def is_valid_pH_step(self):
    #     if self.pH_step < 14.0 and self.pH_step > 0.0:
    #         return True


class ConditionPredictorSetup(models.Model):

    # Optimization parameters
    N_conditions = [('1', 'Top 1'), ('2', 'Top 1 + one more')]
    num_cond = models.CharField("Number of recommendations required, no more than 2:", max_length=1, choices=N_conditions)
    dist_limit = models.FloatField('Cosine distance limit cutoff for Nearest Neighbor in [0, 2], default = 0.3', blank=True)
    outputString = models.BooleanField("Don't output detailed reaction conditions, default")

    ##### Potentially the NN model and the list of corresponding reaction IDs can be varied as well

askcos/askcos_site/main/views/buyables.py
from django.shortcuts import render
from askcos_site.main.views.users import can_modify_buyables

def buyables(request):
    return render(request, 'buyables.html', {'can_modify_buyables': can_modify_buyables(request)})

askcos/askcos_site/main/views/index.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required

def index(request, err=None):
    '''
    Homepage
    '''
    print('{} loaded the index page!'.format(request.user))
    return render(request, 'index.html', {'err': err})

#@login_required
def modules(request, err=None):
    '''list of modules
    '''

    return render(request, 'modules.html', {'err': err})

#@login_required
def faq(request, err=None):
    return render(request, 'faq.html', {'err': err})

#@login_required
def tutorial(request, err=None):
    return render(request, 'tutorial.html', {'err': err})

askcos/askcos_site/main/views/mapping.py
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.conf import settings
import django.contrib.auth.views

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

from ..utils import ajax_error_wrapper, resolve_smiles
from ..forms import DrawingInputForm
import time
from askcos_site.askcos_celery.atom_mapper.atom_mapping_worker import get_atom_mapping
import re


# @login_required
def atom_mapping(request):
    return render(request, 'mapping.html')

@ajax_error_wrapper
def ajax_find_atom_mapping(request):
    '''Perform the forward synthesis'''
    data = {'err': False}

    rxnsmiles = request.GET.get('rxnsmiles', '')

    mapper = request.GET.get('mapper', 'WLN atom mapper')

    print('reactants: {}'.format(rxnsmiles))
    print('mapper: {}'.format(mapper))

    startTime = time.time()

    ## need to work on it
    result = get_atom_mapping.delay(rxnsmiles, mapper=mapper)
    data['rxnsmiles_mapped'] = result.get(10)
    print('---------------------------------')
    print(data)
    print('---------------------------------')

    data['html_time'] = '{:.3f} seconds elapsed'.format(time.time() - startTime)

    if data['rxnsmiles_mapped']:
        url_mapping = reverse('draw_mapped_reaction', kwargs={'smiles': data['rxnsmiles_mapped']})
        url_highlight = reverse('draw_highlighted_reaction', kwargs={'smiles': data['rxnsmiles_mapped']})
        data['html_mapping'] = '<img src="' + url_mapping + '">'
        data['html_highlight'] = '<img src="' + url_highlight + '">'
    else:
        data['html_mapping'] = 'No atom mapping is found'
        data['html_highlight'] = 'No highlighted reaction iamge to show'
    return JsonResponse(data)

askcos/askcos_site/main/templates/retro.html
{% extends "base.html" %}

{% block title %}One-step Retrosynthesis{% endblock %}
{% block page_title %}One-step Retrosynthesis{% endblock %}

{% block extrahead %}{% endblock %}

{% block navbar_items %}
<a href="{% url 'retro_home' %}">One-step Retro</a>
{% endblock %}

{% block sidebar_items %}{% endblock %}


{% block javascript %}
<script>
function showFields(name) {
    if (name=='Relevance') {
        $('#RelevanceSettings1').show();
        $('#RelevanceSettings2').show();
    } else {
        $('#RelevanceSettings1').hide();
        $('#RelevanceSettings2').hide();
    }
}
window.onload = function() {
    // console.log("{{ form.template_prioritization }}");
    showFields("{{ form.template_prioritization }}");
}
function resetSettings() {
    $("#template_count").val(100);
    $("#max_cum_prob").val(0.995);
    $("#filter_threshold").val(0.75);
    showFields("Relevance");
}
function liberalSettings() {
    $("#template_count").val(1000);
    $("#max_cum_prob").val(0.9999);
    $("#filter_threshold").val(0.01);
    showFields("Relevance");
}
</script>
{% endblock %}


{% block page_body %}

<p>Begin by entering in the SMILES string or name of the target molecule, or choose from one of the proposal targets below.</p>

<form method="post" id="smiles_form" action="{% url 'retro_home' %}">
<table class="table table-borderless table-nonfluid">
    <tr>
        <th>Target compound:</th>
        <td>
            <input id="id_smiles" maxlength="400" name="smiles" type="text" value="{{ form.smiles }}"><a class="btn btn-primary" data-toggle="modal" data-target="#drawingbox" onclick="drawBox('id_smiles')" style="margin-left:10px"><span class="glyphicon glyphicon-pencil" style="margin-right:10px"></span>Draw</a>
        </td>
    </tr>
    <!-- Shortcut buttons -->
    <tr><th>Quick settings: </th>
    <td colspan="4">
        <button type="button" style="width:100%" onclick="resetSettings();">Default settings</button>
    </td></tr>
    <tr><th></th><td colspan="4">
        <button type="button" style="width:100%" onclick="liberalSettings();">Idea generation settings</button>
    </td></tr>
    <tr>
        <th>Template prioritization:</td>
        <td>
            <select id="id_template_prioritzation" name="template_prioritization" onchange="showFields(this.options[this.selectedIndex].value)">
                <!-- <option value="Popularity" {% if form.template_prioritization == 'Popularity' %}selected{% endif %}>Apply all templates</option> -->
                <option value="Relevance"  {% if form.template_prioritization == 'Relevance' %}selected{% endif %}>Apply relevant templates</option>
            </select>
        </td>
    </th>
    <tr><th></th>
        <td id="RelevanceSettings1">Num. templates: <input name="template_count" id="template_count" maxlength="6" size="6" type="text" value="{{ form.template_count }}"></td>
    </tr>
    <tr><th></th>
        <td id="RelevanceSettings2">Max. cum. prob.: <input name="max_cum_prob" id="max_cum_prob" maxlength="6" size="6" type="text" value="{{ form.max_cum_prob }}"></td>
    </tr>
    <tr>
        <th>Precursor scoring:</th>
        <td>
            <select id="id_precursor_prioritization" name="precursor_prioritization">
                <option value="Heuristic" {% if form.precursor_prioritization == 'Heuristic' %}selected{% endif %}>Heuristic</option>
                <option value="RelevanceHeuristic" {% if form.precursor_prioritization == 'RelevanceHeuristic' %}selected{% endif %}>Relevance+Heuristic</option>
                <option value="SCScore"  {% if form.precursor_prioritization == 'SCScore' %}selected{% endif %}>SCScore</option>
                <option value="Natural"  {% if form.precursor_prioritization == 'Natural' %}selected{% endif %}>Natural ordering</option>
            </select>
        </td>
    </tr>
    <tr>
        <th></th>
        <td>Min. plausibility: <input name="filter_threshold" id="filter_threshold" maxlength="6" size="6" type="text" value="{{ form.filter_threshold }}"></td>
    </tr>

    <th>{% csrf_token %}</th>
    <td>
        <!-- <input type="submit" value="Search (achiral)" name="retro"> -->
        <!-- <input type="submit" value="Search (literature)" name="retro_lit"> -->
        <input type="submit" value="Search" name="retro">
    </td>
</table>
</form>

{% if suggestions %}
    <table>
    {% for suggestion in suggestions %}
        <tr>
            <td>
                <a href="{% url 'retro_target' suggestion.smiles %}">{{ suggestion.name }}</a><br>
                <a href="{% url 'retro_interactive_mcts_target' suggestion.smiles %}"><i>tree builder</i></a>
            </td>
            <td><img src="{% url 'draw_smiles' suggestion.smiles %}"></td>
        </tr>
    {% endfor %}
    </table>


{% endif %}

{% if target %}
    <h5>Target molecule: <font class="smiles">{{ target.smiles }}</font></h5>
    <img src="{{ target.img }}" alt="{{ target.smiles }}">
    <br>
    <br>
    <i>Results generated in {{ time }} seconds</i>
    <br>
    <br>

    <table class="table table_precursors" id="results">
        <thead>
            <tr>
                <th>Rank</th>
                <th><font class="smiles"><center>Precursor(s)</center></font></th>
                <th>Score</th>
                <th># Examples</th>
                {% if form.template_prioritization == 'Relevance' %}<th>Max template relevance</th>{% endif %}
                {% if form.filter_threshold %}<th>Fast filter score</th>{% endif %}
            </tr>
        </thead>
        <tbody>
        {% for precursor in precursors %}

        <tr>
            <td>{{ precursor.rank }}</td>
            <td>
                {% for mol in precursor.mols %}
                <font class="smiles">
                    {% if lit_only %}
                    <a href="{% url 'retro_lit_target' mol.smiles %}">{{ mol.smiles }}</a><i> ({{ mol.ppg }})</i>
                    {% else %}
                    <a href="{% url 'retro_target' mol.smiles %}">{{ mol.smiles }}</a><i> ({{ mol.ppg }})</i>
                    {% endif %}
                </font>
                {% if not forloop.last %} + {% endif %}{% endfor %}
                <a href="{% url 'context_rxnsmiles_target2' precursor.smiles target.smiles %}">&rarr; ?</a>
                <br>
                <a><img src="" data-async-load="{% url 'draw_highlight' smiles=precursor.mapped_smiles reacting_atoms=precursor.reacting_atoms bonds='false' %}" alt="{{ precursor.smiles }}" onclick="toggle_visibility('expand{{ precursor.rank }}');"></a>
                
                <div id='expand{{ precursor.rank }}' style='display:none'>  
                    {% if precursor.tforms %}
                    <font class="smiles"><b>Based on retrosynthetic transform template(s):</b></font><br>
                    {% for tform in precursor.tforms %}
                        <font class="smiles">
                            <a href="{% url 'template_target' tform.id %}">Template {{ tform.id }} ({{ tform.count }} examples)</a>
                        </font>{% if not forloop.last %}<br>{% endif %}
                    {% endfor %}
                    {% endif %}
                    {% if precursor.rxid %}
                    <font class="smiles"><b>Based on Reaxys reaction ID: <a href="{% url 'rxid_target' precursor.rxid %}">{{ precursor.rxid }}</a></b></font>
                    {% endif %}
                </div>

            </td>
            <td>{{ precursor.score|floatformat:3 }}</td>
            <td>{{ precursor.num_examples }}</td>
            {% if form.template_prioritization == 'Relevance' %}<td>{{ precursor.template_score|floatformat:4 }}</td>{% endif %}
            {% if form.filter_threshold %}<td>{{ precursor.plausibility|floatformat:3 }}</td>{% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

{% if footnote %}
<br>
<div align="center"><i>{{ footnote }}</i></div>
{% endif %}

<!-- drawing box -->
{% include "drawing_modal.html" %}

{% endblock %}

askcos/askcos_site/main/templates/rxid.html
{% extends "base.html" %}

{% block title %}Image{% endblock %}
{% block page_title %}Template source(s){% endblock %}

{% block extrahead %}{% endblock %}

{% block navbar_items %}
{% endblock %}

{% block sidebar_items %}{% endblock %}

{% block page_body %}

{% if err %}
<div class="error">{{ err }}</div>
{% endif %}
{% if warn %}
<div class="warning">{{ warn }}</div>
{% endif %}

{% if rxid %}
<h4>
	Reaxys reaction ID {{ rxid }}: <font class="smiles">{{ rxn_smiles }}</font><br>
</h4> 
{% if num_instances %}
<p>
	{{ num_instances }} total references
</p>
{% endif %}

<img src="{% url 'draw_reaction' rxn_smiles %}" >

{% if suggested_conditions %}
<h4>
	Most popular conditions:
</h4>
<table>
	{% for condition in suggested_conditions %}
	<tr><td>{{ condition }}</td></tr>
	{% endfor %} 
</table>
{% endif %}


{% endif %}
{% endblock %}

askcos/askcos_site/main/templates/tree.html
{% extends "base.html" %}

{% block title %}Synthesis Tree{% endblock %}
{% block page_title %}Synthesis Tree{% endblock %}

{% block extrahead %}{% endblock %}

{% block navbar_items %}
{% endblock %}

{% block sidebar_items %}{% endblock %}

{% block page_body %}
<h2>Target: {{ target }}</h2>

{% for tree in trees %}
<h3>Option {{ forloop.counter }}, score = {{ tree.score }}</h3>
<div class="tree" id="tree{{ forloop.counter }}">
	<ul>
		<li>
			{% include 'tree_child.html' with target=tree %}
		</li>
	</ul>
	<!-- Fix height of tree block -->
	<div class="clear"></div>
</div>
<div class="clear"></div>

{% if not forloop.last %}
<br><br>
{% endif %}

{% endfor %}

{% endblock %}